### Load in NumPy (remember to pip install numpy first)

In [1]:
import numpy as np

### The Basics

In [35]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [36]:
type(a)

numpy.ndarray

In [37]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [38]:
# Get Dimension
a.ndim

1

In [39]:
b.ndim

2

In [18]:
# Get Shape
b.shape

(2, 3)

In [32]:
# Get Type
a.dtype

dtype('int32')

In [40]:
# Get Size
a.itemsize

4

In [29]:
# Get total size
a.nbytes

12

In [41]:
# Get number of elements
a.size

3

In [42]:
np.linspace(0,5) #start,stop,noparts=10

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [43]:
np.linspace(0,5,5) #start,stop,noparts=5

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [46]:
list(np.arange(1,15,2))#start,stop,steps

[1, 3, 5, 7, 9, 11, 13]

In [47]:
np.logspace(0,5,5) #start,stop,noparts=5

array([1.00000000e+00, 1.77827941e+01, 3.16227766e+02, 5.62341325e+03,
       1.00000000e+05])

In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [50]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### Accessing/Changing specific elements, rows, columns, etc

In [51]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [52]:
# Get a specific element [r, c]
a[1, 5]

13

In [53]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [54]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [55]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [56]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [57]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [58]:
# Get specific element (work outside in)
b[0,1,1]

4

In [59]:
# replace 
b[:,1,:] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence.

In [60]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Initializing Different Types of Arrays

In [61]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [63]:
# Any other number
np.full((2,2), 99,int)

array([[99, 99],
       [99, 99]])

In [65]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [64]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [66]:
import numpy as np
# Generate A Random Number From The Normal Distribution
np.random.normal()

-0.16092783016144502

In [67]:
# Generate Four Random Numbers From The Normal Distribution
np.random.normal(size=4)

array([ 0.88999167,  0.906041  , -1.32773666, -0.92280036])

In [68]:
# Generate Four Random Numbers From The Uniform Distribution
np.random.uniform(size=4)

array([0.93648263, 0.56407541, 0.770549  , 0.44100662])

In [69]:
# Generate Four Random Integers Between 1 and 100
np.random.randint(low=1, high=100, size=4)

array([83, 12, 27, 70])

In [70]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.08314669, 0.73451596],
       [0.56739076, 0.61522568],
       [0.97839503, 0.9260016 ],
       [0.22596627, 0.01159873]])

In [71]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 1, -1,  4],
       [ 4, -4,  2],
       [ 1, -4,  2]])

In [73]:
# for a matrix shape of (10,5), assume this is our training example
3+np.random.randn(3,3)

array([[4.42080681, 2.9332202 , 2.72642356],
       [3.44192809, 3.32878212, 1.55278195],
       [3.28044659, 2.58320962, 2.17224812]])

In [74]:
np.sum(np.random.randn(3,3))

-4.089006561814124

In [76]:
# The identity matrix
np.identity(5,int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [78]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [89]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [79]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [80]:
a = np.array([1,2,3])
b = a.view()
b[0] = 100

print(a)

[100   2   3]


### Mathematics

In [81]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [82]:
a + 2

array([3, 4, 5, 6])

In [83]:
a - 2

array([-1,  0,  1,  2])

In [84]:
a * 2

array([2, 4, 6, 8])

In [85]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [86]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [87]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [88]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [117]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [89]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [90]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [133]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [91]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
np.min(stats)

1

In [93]:
np.max(stats, axis=1)

array([3, 6])

In [94]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [96]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [97]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [164]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## numpy.where() in Python

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.
Syntax :numpy.where(condition[, x, y])
Parameters:
condition : When True, yield x, otherwise yield y.

x, y : Values from which to choose. x, y and condition need to be broadcastable to some shape.

Returns:

out : [ndarray or tuple of ndarrays] 
If both x and y are specified, the output array contains elements of x where condition is True, and elements from y elsewhere.

If only condition is given, return the tuple condition.nonzero(), the indices where condition is True.

In [98]:
# Python program explaining
# where() function

import numpy as np

np.where([[True, False], [True, True]],
		[[1, 2], [3, 4]], [[5, 6], [7, 8]])


array([[1, 6],
       [3, 4]])

In [99]:
# Python program explaining
# where() function

import numpy as np

# a is an array of integers.
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a)

print ('Indices of elements <4')

b = np.where(a<4)
print(b)

print("Elements which are <4")
print(a[b])


[[1 2 3]
 [4 5 6]]
Indices of elements <4
(array([0, 0, 0], dtype=int32), array([0, 1, 2], dtype=int32))
Elements which are <4
[1 2 3]


## numpy.any() in Python

The numpy.any() function tests whether any array elements along the mentioned axis evaluate to True.
Syntax :

numpy.any(a,
          axis = None,
          out = None,
          keepdims = class numpy._globals._NoValue at 0x40ba726c)

### Parameters :

array    :[array_like]Input array or object whose elements, we need to test.
    
axis     : [int or tuple of ints, optional]Axis along which array elements 
     are evaluated.
     The default (axis = None) is to perform a logical AND over all the dimensions of the input
     array. Axis may be negative, in which case it counts from the last to the first axis.
        
out      : [ndarray, optional]Output array with same dimensions as Input array, 
     placed with result
        
keepdmis : [boolean, optional]If this is set to True, the axes which are 
     reduced are left in the result as dimensions with size one. With this option, the result 
     will broadcast correctly against the input array.
     If the default value is passed, then keepdims will not be passed through to the all 
     method of sub-classes of ndarray, however any non-default value will be. If the 
     sub-classes sum method does not implement keepdims any exceptions will be raised.
        
        
### Return :

A new Boolean array as per 'out' parameter

In [101]:
# Python Program illustrating
# numpy.any() method
	
import numpy as np
	
# Axis = NULL
# True False
# True True
# True : False = True (OR)

print("Bool Value with axis = NONE : ",
	np.any([[True,False],[True,True]]))

# Axis = 0
# True False
# True True
# True : False
print("\nBool Value with axis = 0 : ",
	np.any([[True,False],[True,True]], axis = 0))

print("\nBool : ", np.any([-1, 4, 5]))


# Not a Number (NaN), positive infinity and negative infinity
# evaluate to True because these are not equal to zero.
print("\nBool : ", np.any([1.0, np.nan]))

print("\nBool Value : ", np.any([[0, 0],[0, 0]]))

a=np.array([0,1,-1])
np.any(a<0)

Bool Value with axis = NONE :  True

Bool Value with axis = 0 :  [ True  True]

Bool :  True

Bool :  True

Bool Value :  False


True

In [17]:
# Python Program illustrating
# numpy.any() method

# Parameter : keepdmis	
			
import numpy as np

# setting keepdmis = True
print("\nBool Value : ", np.any([[1, 0],[0, 4]], 0))


# setting keepdmis = True
print("\nBool Value : ", np.any([[0, 0],[0, 0]], 0))



Bool Value :  [ True  True]

Bool Value :  [False False]


## numpy.all() in Python

The numpy.all() function tests whether all array elements along the mentioned axis evaluate to True.

### Syntax: 
numpy.all(array,
                    axis = None,
                    out = None,
                    keepdims = class numpy._globals._NoValue at 0x40ba726c)
    
### parameters
array    :[array_like]Input array or object whose elements, we need to test.
axis     : [int or tuple of ints, optional]Axis along which array elements 
     are evaluated.
     The default (axis = None) is to perform a logical AND over all the dimensions of the input
     array. Axis may be negative, in which case it counts from the last to the first axis.
out      : [ndarray, optional]Output array with same dimensions as Input array, 
     placed with result
keepdmis : [boolean, optional]If this is set to True, the axes which are 
     reduced are left in the result as dimensions with size one. With this option, the result 
     will broadcast correctly against the input array.
     If the default value is passed, then keepdims will not be passed through to the all 
     method of sub-classes of ndarray, however any non-default value will be. If the 
     sub-classes sum method does not implement keepdims any exceptions will be raised.

### Return :

A new Boolean array as per 'out' parameter

In [102]:
# Python Program illustrating
# numpy.all() method
	
import numpy as np
	
# Axis = NULL
# True False
# True True
# True : False = False

print("Bool Value with axis = NONE : ",
	np.all([[True,False],[True,True]]))

# Axis = 0
# True False
# True True
# True : False
print("\nBool Value with axis = 0 : ",
	np.all([[True,False],[True,True]], axis = 0))

print("\nBool : ", np.all([-1, 4, 5,0]))


# Not a Number (NaN), positive infinity and negative infinity
# evaluate to True because these are not equal to zero.
print("\nBool : ", np.all([1.0, np.nan]))

print("\nBool Value : ", np.all([[0, 0],[0, 0]]))


Bool Value with axis = NONE :  False

Bool Value with axis = 0 :  [ True False]

Bool :  False

Bool :  True

Bool Value :  False


In [16]:
# Python Program illustrating
# numpy.all() method

# Parameter : keepdmis	
			
import numpy as np

# setting keepdmis = True
print("\nBool Value : ", np.all([[1, 0],[0, 4]], 0))


# setting keepdmis = True
print("\nBool Value : ", np.all([[0, 0],[0, 0]], 0))



Bool Value :  [False False]

Bool Value :  [False False]


### argpartition()
NumPy has this amazing function which can find N largest values index. The output will be the N largest values index, and then we can sort the values if needed.


In [103]:
x = np.array([12, 10, 12, 0, 6, 8, 9, 1, 16, 4, 6, 0])
print(np.argpartition(x, -4))
index_val = np.argpartition(x, -4)[-4:]
index_val
# array([1, 8, 2, 0], dtype=int64)


[ 7 11 10  3  4  9  5  6  1  8  2  0]


array([1, 8, 2, 0], dtype=int32)

In [25]:
np.sort(x[index_val])
# array([10, 12, 12, 16])

array([10, 12, 12, 16])

### allclose()
Allclose() is used for matching two arrays and getting the output in terms of a boolean value. It will return False if items in two arrays are not equal within a tolerance. It is a great way to check if two arrays are similar, which can actually be difficult to implement manually.

In [107]:
array1 = np.array([0.12,0.17,0.24,0.29])
array2 = np.array([0.13,0.19,0.26,0.31])
# with a tolerance of 0.1, it should return False:
np.allclose(array1,array2,0.1)
# False


False

In [27]:
# with a tolerance of 0.2, it should return True:
np.allclose(array1,array2,0.2)
# True

True

### clip()
Clip() is used to keep values in an array within an interval. Sometimes, we need to keep the values within an upper and lower limit. For the mentioned purpose, we can make use of NumPy’s clip(). Given an interval, values outside the interval are clipped to the interval edges.

In [28]:
x = np.array([3, 17, 14, 23, 2, 2, 6, 8, 1, 2, 16, 0])
np.clip(x,2,5)
# array([3, 5, 5, 5, 2, 2, 5, 5, 2, 2, 5, 2])

array([3, 5, 5, 5, 2, 2, 5, 5, 2, 2, 5, 2])

### extract()
Extract() as the name goes, is used to extract specific elements from an array based on a certain condition. With extract(), we can also use conditions like and and or.

In [29]:
# Random integers
array = np.random.randint(20, size=12)
array

array([ 8,  5, 16, 18,  4,  8,  3, 18, 13,  6, 13, 12])

In [30]:
#  Divide by 2 and check if remainder is 1
cond = np.mod(array, 2)==1
cond

array([False,  True, False, False, False, False,  True, False,  True,
       False,  True, False])

In [31]:
# Use extract to get the values
np.extract(cond, array)

array([ 5,  3, 13, 13])

In [32]:
# Apply condition on extract directly
np.extract(((array < 3) | (array > 15)), array)

array([16, 18, 18])

### percentile()
Percentile() is used to compute the nth percentile of the array elements along the specified axis.

In [34]:
a = np.array([1,5,6,8,1,7,3,6,9])
print("50th Percentile of a, axis = 0 : ",  
      np.percentile(a, 50, axis =0))
# 50th Percentile of a, axis = 0 :  6.0
b = np.array([[10, 7, 4], [3, 2, 1]])
print("30th Percentile of b, axis = 0 : ",  
      np.percentile(b, 30, axis =0))
# 30th Percentile of b, axis = 0 :  [5.1 3.5 1.9]

50th Percentile of a, axis = 0 :  6.0
30th Percentile of b, axis = 0 :  [5.1 3.5 1.9]


### Miscellaneous
##### Load Data from File

In [179]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [196]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])